units ="[{label: 'ft',value: 'ft', },{ label: 'meter',value: 'meter',},{label: 'acre',value: 'acre', }, {label: 'hector',value: 'hector',},]"

homeData = "[{label: '🏠  Apartment',value: 'Apartment',},{ label: '🏠  House', value: 'House',}, {  label: '🏠  Land', value: 'Land', },{label: '🏠  Shop', value: 'Shop', }, {label: '🏠  Building', value: 'Building',},{label: '🏠  Plot',value: 'Plot',},{label: '🏠  Agriculture Land',value: 'Agriculture Land',},{label: '🏠  Villa',value: 'Villa',},]"

purpose = "[{label: '💲  FOR RENT', value: 'FOR RENT',}, {label: '💲  FOR SALE',value: 'FOR SALE', },{label: 'All',value: 'All', },]"

location = "[ {label: '🏛️  Kafr El Sheikh', value: 'Kafr El Sheikh'},{label: '🏛️  Alexandria', value: 'Alexandria'},{label: '🏛️  Aswan', value: 'Aswan'},{label: '🏛️  Asyut', value: 'Asyut'},{label: '🏛️  Beheira', value: 'Beheira'},{label: '🏛️  Beni Suef', value: 'Beni Suef'},{label: '🏛️  Cairo', value: 'Cairo'},{label: '🏛️  Dakahlia', value: 'Dakahlia'},{label: '🏛️  Damietta', value: 'Damietta'}, {label: '🏛️  Faiyum', value: 'Faiyum'}, {label: '🏛️  Gharbia', value: 'Gharbia'}, {label: '🏛️  Giza', value: 'Giza'}, {label: '🏛️  Ismailia', value: 'Ismailia'},{label: '🏛️  Luxor', value: 'luxor'},{label: '🏛️  Matruh', value: 'Matruh'},{label: '🏛️  Minya', value: 'Minya'},{label: '🏛️  Monufia', value: 'Monufia'},{label: '🏛️  New Valley', value: 'New Valley'},{label: '🏛️  North Sinai', value: 'North Sinai'},{label: '🏛️  Port Said', value: 'Port Said'},{label: '🏛️  Qalyubia', value: 'Qalyubia'}, {label: '🏛️  Qena', value: 'Qena'},{label: '🏛️  Red Sea', value: 'Red Sea'},{label: '🏛️  Sharqia', value: 'Sharqia'},{label: '🏛️  Sohag', value: 'Sohag'}, {label: '🏛️  South Sinai', value: 'South Sinai'},{label: '🏛️  Suez', value: 'Suez'},]"


units = "[{label: 'قدم',value: 'ft',},{label: 'متر',value: 'meter',},{label: 'فدان',value: 'acre',},{label: 'هيكتور',value: 'hector',},]"

homeData = "[{label: 'شقة  🏠',value: 'Apartment',},{ label: 'بيت  🏠',value: 'House',},{label: 'قطعة ارض  🏠',value: 'Land',},{label: 'محل  🏠',value: 'Shop',},{label: 'بناء  🏠'  ,value: 'Building',},{ label: 'قطعة ارض  🏠',value: 'Plot',},{ label: 'ارض زراعية  🏠',value: 'Agriculture Land',},{label: 'فيلا  🏠',value: 'Villa',},]"

purpose = "[{label: 'للبيع  💲',value: 'FOR RENT',},{label: 'للايجار  💲',value: 'FOR SALE',},{label: 'الكل', value: 'All',},]"

location = "[{label: 'كفرالشيخ  🏛️', value: 'Kafr El Sheikh'},{label: 'اسكندرية  🏛️', value: 'Alexandria'},{label: 'اسوان  🏛️', value: 'Aswan'},{label: 'اسيوط  🏛️', value: 'Asyut'},{label: 'البحيرة  🏛️', value: 'Beheira'},{label: 'بني سويف  🏛️', value: 'Beni Suef'}, {label: 'القاهرة  🏛️', value: 'Cairo'},{label: 'الدقهلية  🏛️', value: 'Dakahlia'}, {label: 'دمياط  🏛️', value: 'Damietta'}, {label: 'الفيوم  🏛️', value: 'Faiyum'},{label: 'الغربية  🏛️', value: 'Gharbia'},{label: 'الجيزة  🏛️', value: 'Giza'},{label: 'الاسماعيلية  🏛️', value: 'Ismailia'}, {label: 'الاقصر  🏛️', value: 'luxor'},{label: 'مطروح  🏛️', value: 'Matruh'},{label: 'المنيا  🏛️', value: 'Minya'},{label: 'المنوفية  🏛️', value: 'Monufia'},{label: 'الوادي الجديد  🏛️', value: 'New Valley'},{label: 'شمال سيناء  🏛️', value: 'North Sinai'},{label: 'بورسعيد  🏛️', value: 'Port Said'},{label: 'القليوبية  🏛️', value: 'Qalyubia'},{label: 'قنا  🏛️', value: 'Qena'},{label: 'البحر الاحمر  🏛️', value: 'Red Sea'},{label: 'الشرقية  🏛️', value: 'Sharqia'},{label: 'سوهاج  🏛️', value: 'Sohag'}, {label: 'جنوب سيناء  🏛️', value: 'South Sinai'},{label: 'السويس  🏛️', value: 'Suez'},]"
